config/routes.rb
Realitylabs::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "start_league" => 'leagues#new', :as => 'start_league'
  post "leagues/:id/start_draft" => 'leagues#start_draft', :as => 'start_draft'
  get 'leagues/:id/draft' => 'leagues#draft', :as => 'draft'
  post "leagues/:id/add_to_team" => 'leagues#add_to_team', :as => 'add_to_team'  
  post "users/:id/delete_user" => 'users#delete_user', :as => 'delete_user'
  get 'users/:id/first_visit' => 'users#first_visit', :as => 'first_visit'
  post 'check_username' => 'users#check_username', :as => 'check_username'
  post 'leagues/check_league_name' => 'leagues#check_league_name', :as => 'check_league_name'
  post 'leagues/:id/end_draft' => 'leagues#end_draft', :as => 'end_draft'

  match 'contestants/add_round' => 'contestants#add_round'
  match 'contestants/update_round' => 'contestants#update_round'
  match 'contestants/reverse_round' => 'contestants#reverse_round'
  match '/admin' => 'contestants#index'
  match 'leagues/:id/add_to_team' => 'leagues#add_to_team'

  resources :users, :sessions, :password_resets
  resources :contestants do
    collection do
      get 'add_round'
      put 'update_round'
      get 'reverse_round'
    end
  end
  resources :leagues do
    member do
      get 'draft'
      get 'draft_preview'
    end
  end

  root :to => 'welcome#index'

end

app/models/contestant.rb
require 'rake'
class Contestant < ActiveRecord::Base
	attr_accessible :name, :survive, :immunity, :merger, :final_three, :winner, :round, :occupation, :tribe, :hometown, :labwork, :nickname, :preseason_rank, :age

	def self.rake_db_copy
	    # load File.join(Rails.root, 'lib', 'tasks', 'tempfile.rake')
	    # Rake::Task['db:data:dump_dir'].invoke

	    # Looks to see if the database copy already exists.  If so, it deletes it and puts the new copy in.
	    @round = Contestant.first.round
	    @time = Time.now.to_s.gsub!(/ /, '_')
	    @dir = Dir.entries("db").select {|x| x =~ /^round#{@round}/}.join
	    	if @dir != ""
	    		system("rm -rf db/#{@dir}")
	    		# @dir.each do |directory|
				# system("rm -rf db/#{directory.to_s}")
				# end
			end
	    system("rake db:data:dump_dir dir=round#{@round}_#{@time}") #Apparently this isn't the most efficient way to do this, as it loads a new instance of rails or something like that.  It is working for the time being.
	    # system("rake db:data:dump_dir dir=round#{@round}")
  	end

  	def self.rake_db_load # This reloads the results of the previous round.
  		@last_round = Contestant.first.round - 1
  		@dir = Dir.entries("db").select{|x| x =~ /^round#{@last_round}/}.join
  		system("rake db:data:load_dir dir=#{@dir}")
  	end
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
	http_basic_authenticate_with :name => "admin", :password => "admin"

	def index 
		@contestants = Contestant.all
		@round = @contestants[0].round
	end

	def admin 
		@contestants = Contestant.all
		@round = @contestants[0].round
	end

	def add_round
		@contestants = Contestant.all
		@round = @contestants[0].round
	end

	def update_round
		# This creates a back-up file to replace the one that was created at the end of the last 'update_round' action.  It's in here so that if leagues and users are created in-between rounds and then we need to 'reverse_round', we don't lose all that data.  
		Contestant.rake_db_copy
		
		@con = Contestant.all
		@next_round = @con[0].round + 1
		@conditions = ['survive', 'immunity', 'merger', 'final_three', 'winner']
		@array = []
		@con.each do |x|
			@conditions.each do |y|
				x.update_attribute("#{y}", params[:contestant]["#{x.id}_#{y}"])
				@array << params[:contestant]["#{x.id}_#{y}"]
			end
			
			
			x.update_attribute("round", @next_round)
		end

		# User.add_column # This is what builds and runs the new migration file that will add a new column to the User model ActiveRecord.  It runs the migration, with no default value. 
		# User.reload
		@users = User.all
		@users.each do |user|
			user.update_attribute("score_round#{Contestant.first.round}", "#{user.score}")
		end

		

		# @params = params[:contestant].inspect
		Contestant.rake_db_copy
		redirect_to contestants_path
	end

	def reverse_round
		# This loads the info from the last round.
		@round = Contestant.first.round
		@last_round = @round - 1
		@dir = Dir.entries("db").select {|x| x =~ /^round#{@last_round}/}.join
		system("rake db:data:load_dir dir=#{@dir}")

		# This renames the dirname of the incorrect copy.  I'm leaving the filename of the migration alone, because it will need to be created anyway and doesn't seem to hurt anything being left in.
		@dir = Dir.entries("db").select {|x| x =~ /^round#{@round}/}.join
		File.rename "db/#{@dir}", "db/reverse_#{@dir}"
		redirect_to contestants_path
	end

	def new
    # default: render 'new' template
	end

	def create
	  @contestant = Contestant.new(params[:contestant])
	  @contestant.update_attributes(:round => 0, :survive => 1, :merger => 0, :immunity => 0, :final_three => 0, :winner => 0)
	  @contestant.save
	  flash[:notice] = "#{@contestant.name} was successfully created."
	  redirect_to contestants_path
	end

	def edit
	  @contestant = Contestant.find params[:id]
	end

	def update
	  @contestant = Contestant.find params[:id]
	  @contestant.update_attributes!(params[:contestant])
	  flash[:notice] = "#{@contestant.title} was successfully updated."
	  redirect_to contestant_path(@contestant)
	end

	def destroy
	  @contestant = Contestant.find(params[:id])
	  @contestant.destroy
	  flash[:notice] = "contestant '#{@contestant.title}' deleted."
	  redirect_to contestants_path
	end
end

app/views/contestants/add_round.html.haml
%h1 Add Results from Elimination Round #{@round + 1}
/ - @contestants.each do |contestant|
/ 	%h2= contestant.name

= form_for :contestant, :url => '/contestants/update_round', :method => :put do |x|
	%table
		%thead
			%tr
				%th Contestant
				%th Survive
				%th Immunity
				%th Merger
				%th Final Three
				%th Winner
		%tbody
			- @contestants.each do |contestant|
				%tr
					%td= contestant.name 
					%td
						/ = x.label :survive
						= x.check_box "#{contestant.id}_survive", :checked => contestant.survive 
					%td
						/ = x.label :immunity
						= x.check_box "#{contestant.id}_immunity"
					%td
						/ = x.label :merger
						= x.check_box "#{contestant.id}_merger" 
					%td
						/ = x.label :final_three
						= x.check_box "#{contestant.id}_final_three"
					%td
						/ = x.label :winner
						= x.check_box "#{contestant.id}_winner" 
	= submit_tag 'Add New Round Information'

app/views/contestants/admin.html.haml
%h1 Hello World!!!
%p 
  This is just some rando text I'm throwing up to illustrate that everything's working as it should.  Holla!  This page should appear in /contestants as the index page.


%h1 Round #{@round}
%table#leagues
  %thead
    %tr
      %th Contestant Name
      %th Survive
      %th Immunity
      %th Merger
      %th Final Three
      %th Winner
  %tbody
    - @contestants.each do |contestant|
      %tr
        %td{:id => contestant.name.downcase.gsub(/ /, '')}= contestant.name 
        %td{:id => [contestant.name.downcase.gsub(/ /, ''), "survive"]}= contestant.survive 
        %td{:id => [contestant.name.downcase.gsub(/ /, ''), "immunity"]}= contestant.immunity
        %td{:id => [contestant.name.downcase.gsub(/ /, ''), "merger"]}= contestant.merger
        %td{:id => [contestant.name.downcase.gsub(/ /, ''), "final_three"]}= contestant.final_three
        %td{:id => [contestant.name.downcase.gsub(/ /, ''), "winner"]}= contestant.winner

%h2= link_to 'Update Round', add_round_contestants_path
= link_to 'Oops - reset last round', reverse_round_contestants_path

app/views/contestants/edit.html.haml
%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/contestants/index.html.haml
%h1 Hello World!!!
%p 
  This is just some rando text I'm throwing up to illustrate that everything's working as it should.  Holla!  This page should appear in /contestants as the index page.


%h1 Round #{@round}
%table#leagues
  %thead
    %tr
      %th Contestant Name
      %th Survive
      %th Immunity
      %th Merger
      %th Final Three
      %th Winner
  %tbody
    - @contestants.each do |contestant|
      %tr
        %td{:id => contestant.name.downcase.gsub(/ /, '')}= contestant.name 
        %td{:id => [contestant.name.downcase.gsub(/ /, ''), "survive"]}= contestant.survive 
        %td{:id => [contestant.name.downcase.gsub(/ /, ''), "immunity"]}= contestant.immunity
        %td{:id => [contestant.name.downcase.gsub(/ /, ''), "merger"]}= contestant.merger
        %td{:id => [contestant.name.downcase.gsub(/ /, ''), "final_three"]}= contestant.final_three
        %td{:id => [contestant.name.downcase.gsub(/ /, ''), "winner"]}= contestant.winner

%h2= link_to 'Update Round', add_round_contestants_path
= link_to 'Oops - reset last round', reverse_round_contestants_path

app/views/contestants/new.html.haml
%h1 Add Contestant

= form_tag contestants_path do

  = label :contestant, :name, 'First and Last'
  = text_field :contestant, 'name'

  = submit_tag 'Add New Contestant'

app/views/contestants/round.html.haml
%h1 Add Results from Elimination Round
%p These should be the results from Round #{Contestant.find_by_id(1).round}.

= form_tag update_round_contestants_path, :method => :put do

%ul
  - @contestants.each do |contestant|
        %li contestant.name

  / = label :movie, :title, 'Title'
  / = text_field :movie, 'title'

  / = label :movie, :rating, 'Rating'
  / = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  / = label :movie, :director, 'Director'
  / = text_field :movie, 'director'

  / = label :movie, :release_date, 'Released On'
  / = date_select :movie, :release_date

  = submit_tag 'Add New Round Information'

app/views/contestants/update_round.html.haml
%h1 This is the view for the update_round action in the contestants_controller.  Just using it to view the params...
%h2= @array