config/routes.rb
Realitylabs::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "start_league" => 'leagues#new', :as => 'start_league'
  post "leagues/:id/start_draft" => 'leagues#start_draft', :as => 'start_draft'
  get 'leagues/:id/draft' => 'leagues#draft', :as => 'draft'
  post "leagues/:id/add_to_team" => 'leagues#add_to_team', :as => 'add_to_team'  
  post "users/:id/delete_user" => 'users#delete_user', :as => 'delete_user'
  get 'users/:id/first_visit' => 'users#first_visit', :as => 'first_visit'
  post 'check_username' => 'users#check_username', :as => 'check_username'
  post 'leagues/check_league_name' => 'leagues#check_league_name', :as => 'check_league_name'
  post 'leagues/:id/end_draft' => 'leagues#end_draft', :as => 'end_draft'

  match 'contestants/add_round' => 'contestants#add_round'
  match 'contestants/update_round' => 'contestants#update_round'
  match 'contestants/reverse_round' => 'contestants#reverse_round'
  match '/admin' => 'contestants#index'
  match 'leagues/:id/add_to_team' => 'leagues#add_to_team'

  resources :users, :sessions, :password_resets
  resources :contestants do
    collection do
      get 'add_round'
      put 'update_round'
      get 'reverse_round'
    end
  end
  resources :leagues do
    member do
      get 'draft'
      get 'draft_preview'
    end
  end

  root :to => 'welcome#index'

end

app/models/league.rb
class League < ActiveRecord::Base
	attr_accessible :name, :confirmation_code, :username, :password, :league_id, :contestant_pool, :scoring_system, :draft_order, :draft_active, :draft_round, :draft_start, :team_size
	has_many :users
	# @hash = {}
	# @contestants = Contestant.all
	# @contestants.each do |x|
	# 	@hash.merge!(x.name => x.survive)
	# end
	
	serialize :contestant_pool, Hash 
	serialize :scoring_system, Hash
	serialize :draft_order, Array
	
	validates_presence_of :confirmation_code, :on => :save
	validates :name, :length => { :maximum => 30 }, :uniqueness => true, :allow_blank => false, :presence => true

	# This is the method by which we'll return a hash with each username as a key and their total_score as a value.
	def scoreboard
		@scoreboard = {}
		self.users.each do |user|
			# @hash = {user.username => user.total_score}
			@scoreboard.merge!(user.username => user.total_score)
		end
		return @scoreboard
	end

	# This is the draft method.
	def auto_draft(user)
		user = User.find_by_username(user)
		if user.online == false 
			choice = self.contestant_pool.reject{|key, value| value == false}.keys.sample
			team = user.team << choice
			user.update_attribute("team", team)
			self.contestant_pool[choice] = false
			next_round = self.draft_round + 1
			self.update_attribute("draft_round", next_round)				
    		choice = choice.gsub(" ", "_")
    		system(%Q[curl http://realitylabs-server.herokuapp.com/faye -d 'message={"channel":"/#{self.id}/draft/auto_pick", "data":"data"}'])
		end
	end

	def test
		teamsize = self.users[0].team.size
		puts teamsize
		20.times do
			newsize = self.users[0].team.size
			if newsize > teamsize
				puts "working"
				break
			else
				puts newsize
			end
			sleep(1)
			self.users[0].reload
		end
	end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
	def online(user)
		if user.online == true
			capture_haml do
				haml_tag :td, "#{user.username}"
			end
		else
			capture_haml do
				haml_tag :td, nil
			end
		end
	end

	def offline(user)
		if user.online == false
			capture_haml do
				haml_tag :td, "#{user.username}"
			end
		else
			capture_haml do
				haml_tag :td, nil
			end
		end
	end

	def draft_order_head
		capture_haml do
			n = @nrounds
			for i in 1..n
			  haml_tag :th, "Round #{i}"
			end
		end
	end

	def draft_order_body
		capture_haml do
			n = @nusers
			for i in 1..n
				haml_tag :tr
			end
		end
	end

	def draft_order_helper
		haml_tag :h2, "Draft Order"
		for i in 0...@nrounds
			haml_tag :div, :class => "draft_list" do
				haml_tag :h3, "Round " + (i+1).to_s
				haml_tag :ul do
					for n in 0...@nusers
						haml_tag :li, @draft_order[((@nusers*i)+n)]
					end
				end				
			end
		end
		haml_tag :div, :class => "clear"
		haml_tag :div, :class => "placeholder"
	end

	def draft_order
		capture_haml do
			if @nrounds == 1
				haml_tag :div, :class => "draft_order", :style => "width: 110px" do 
      				draft_order_helper
      			end
      		elsif @nrounds == 2 || @nrounds == 4
      			haml_tag :div, :class => "draft_order", :style => "width: 220px" do 
      				draft_order_helper
      			end
      		elsif @nrounds == 3 || @nrounds == 6
      			haml_tag :div, :class => "draft_order", :style => "width: 330px" do 
      				draft_order_helper
      			end
      		elsif @nrounds == 7 || @nrounds == 8
      			haml_tag :div, :class => "draft_order", :style => "width: 440px" do 
      				draft_order_helper
      			end      				
			elsif @nrounds == 9 || @nrounds == 10
	      		haml_tag :div, :class => "draft_order", :style => "width: 550px" do 
	      			draft_order_helper
	      		end
	      	else @nrounds > 10
	      		haml_tag :div, :class => "draft_order", :style => "width: 660px" do 
	      			draft_order_helper
	      		end
    #   			haml_tag :h2, "Draft Order"
				# for i in 0...@nrounds
				# 	haml_tag :div, :class => "draft_list" do
				# 		haml_tag :h3, "Round " + (i+1).to_s
				# 		haml_tag :ul do
				# 			for n in 0...@nusers
				# 				haml_tag :li, @draft_order[((@nusers*i)+n)]
				# 			end
				# 		end				
				# 	end
				# end
				# haml_tag :div, :class => "clear"
				# haml_tag :div, :class => "placeholder"
			end
		end
	end

	def draft_board
		capture_haml do
			haml_tag :table, :id => "draft_table", :class => "draft_table" do
				haml_tag :colgroup, :span => (@nrounds + 1)
				haml_tag :thead, :id => "draft_table_head" do
					haml_tag :tr, :class => "draft_table_header" do
						haml_tag :th, :colspan => "#{@nrounds + 1}" do 
							haml_tag :h2, "User Picks Each Round"
						end
					end
					haml_tag :tr do
						haml_tag :th do 
							haml_tag :h3, "Username"
						end
						n = @nrounds
						for i in 1..n
							haml_tag :th, :class => "draft_table_round_num" do
								haml_tag :h3, "#{i}"
							end
						end
					end
				end
				haml_tag :tbody, :id => "draft_table_body" do
					n = @nusers
					for i in 0...n
						haml_tag :tr, :id => "#{@users[i].username}_pick" do
							haml_tag :td, :class => "username" do
								haml_tag :h3, "#{@users[i].username}" 
							end 
							n = @nrounds
							for x in 0...n
								if "#{@users[i].team[x]}" == ''
									haml_tag :td 
								else 
									haml_tag :td do
										haml_concat "#{@users[i].team[x]}"
									end
								end
								# haml_tag :td
							end
						end
					end
				end
			end
		end
	end

	def contestant_pool
		capture_haml do
			@pool.each do |member|
				if (@pool.index(member) % 3) == 0
					haml_tag :div, :class => 'left_col' do
						if @league.contestant_pool[member] == true
							haml_tag :button, :id => member.gsub(" ", "_"), :class => 'available' do
								filename = "contestants/" + member.gsub(" ", "_") + ".jpg"
								haml_concat image_tag filename
								haml_tag :h4, member
							end
							haml_tag :div, :class => 'cast_bio_draft', :id => (member.gsub(" ", "_") + "_bio") do
							# contestant = Contestant.find_by_name(member)
							# haml_tag :p do
							# 	haml_tag :strong, contestant.nickname
							# 	haml_tag :br
							# 	haml_tag :b, "Tribe"
							# 	haml_tag :span, contestant.tribe
							# 	haml_tag :br
							# 	haml_tag :b, "Age"
							# 	haml_tag :span, contestant.age
							# 	haml_tag :br
							# 	haml_tag :b, "Hometown"
							# 	haml_tag :span, contestant.hometown
							# 	haml_tag :br
							# 	haml_tag :b, "Occupation"
							# 	haml_tag :span, contestant.occupation
							# 	haml_tag :br
							# 	haml_tag :b, "Reality Labs Pre-Season Rank"
							# 	haml_tag :span, contestant.preseason_rank
							# 	haml_tag :br
							# 	haml_tag :b, "The Lab Work"
							# 	haml_tag :span, :class => 'bio_float' do 
							# 		haml_concat contestant.labwork
							# 	end
							# 	haml_tag :br
							# end
							end
						else
							haml_tag :button, :id => member.gsub(" ", "_"), :class => 'unavailable' do
								filename = "contestants/" + member.gsub(" ", "_") + ".jpg"
								haml_concat image_tag filename
								haml_tag :h4, member
							end
							haml_tag :div, :class => 'cast_bio_draft', :id => (member.gsub(" ", "_") + "_bio") do
							# contestant = Contestant.find_by_name(member)
							# haml_tag :p do
							# 	haml_tag :strong, contestant.nickname
							# 	haml_tag :br
							# 	haml_tag :b, "Tribe"
							# 	haml_tag :span, contestant.tribe
							# 	haml_tag :br
							# 	haml_tag :b, "Age"
							# 	haml_tag :span, contestant.age
							# 	haml_tag :br
							# 	haml_tag :b, "Hometown"
							# 	haml_tag :span, contestant.hometown
							# 	haml_tag :br
							# 	haml_tag :b, "Occupation"
							# 	haml_tag :span, contestant.occupation
							# 	haml_tag :br
							# 	haml_tag :b, "Reality Labs Pre-Season Rank"
							# 	haml_tag :span, contestant.preseason_rank
							# 	haml_tag :br
							# 	haml_tag :b, "The Lab Work"
							# 	haml_tag :span, :class => 'bio_float' do 
							# 		haml_concat contestant.labwork
							# 	end
							# 	haml_tag :br
							# end
							end
						end
					end
				elsif (@pool.index(member) % 3) == 1
					haml_tag :div, :class => 'center_col' do
						if @league.contestant_pool[member] == true
							haml_tag :button, :id => member.gsub(" ", "_"), :class => 'available' do
								filename = "contestants/" + member.gsub(" ", "_") + ".jpg"
								haml_concat image_tag filename
								haml_tag :h4, member
							end
							haml_tag :div, :class => 'cast_bio_draft', :id => (member.gsub(" ", "_") + "_bio") do
							# contestant = Contestant.find_by_name(member)
							# haml_tag :p do
							# 	haml_tag :strong, contestant.nickname
							# 	haml_tag :br
							# 	haml_tag :b, "Tribe"
							# 	haml_tag :span, contestant.tribe
							# 	haml_tag :br
							# 	haml_tag :b, "Age"
							# 	haml_tag :span, contestant.age
							# 	haml_tag :br
							# 	haml_tag :b, "Hometown"
							# 	haml_tag :span, contestant.hometown
							# 	haml_tag :br
							# 	haml_tag :b, "Occupation"
							# 	haml_tag :span, contestant.occupation
							# 	haml_tag :br
							# 	haml_tag :b, "Reality Labs Pre-Season Rank"
							# 	haml_tag :span, contestant.preseason_rank
							# 	haml_tag :br
							# 	haml_tag :b, "The Lab Work"
							# 	haml_tag :span, :class => 'bio_float' do 
							# 		haml_concat contestant.labwork
							# 	end
							# 	haml_tag :br
							# end
							end
						else
							haml_tag :button, :id => member.gsub(" ", "_"), :class => 'unavailable' do
								filename = "contestants/" + member.gsub(" ", "_") + ".jpg"
								haml_concat image_tag filename
								haml_tag :h4, member
							end
							haml_tag :div, :class => 'cast_bio_draft', :id => (member.gsub(" ", "_") + "_bio") do
							# contestant = Contestant.find_by_name(member)
							# haml_tag :p do
							# 	haml_tag :strong, contestant.nickname
							# 	haml_tag :br
							# 	haml_tag :b, "Tribe"
							# 	haml_tag :span, contestant.tribe
							# 	haml_tag :br
							# 	haml_tag :b, "Age"
							# 	haml_tag :span, contestant.age
							# 	haml_tag :br
							# 	haml_tag :b, "Hometown"
							# 	haml_tag :span, contestant.hometown
							# 	haml_tag :br
							# 	haml_tag :b, "Occupation"
							# 	haml_tag :span, contestant.occupation
							# 	haml_tag :br
							# 	haml_tag :b, "Reality Labs Pre-Season Rank"
							# 	haml_tag :span, contestant.preseason_rank
							# 	haml_tag :br
							# 	haml_tag :b, "The Lab Work"
							# 	haml_tag :span, :class => 'bio_float' do 
							# 		haml_concat contestant.labwork
							# 	end
							# 	haml_tag :br
							# end
							end
						end
					end
				else
					haml_tag :div, :class => 'right_col' do
						if @league.contestant_pool[member] == true
							haml_tag :button, :id => member.gsub(" ", "_"), :class => 'available' do
								filename = "contestants/" + member.gsub(" ", "_") + ".jpg"
								haml_concat image_tag filename
								haml_tag :h4, member
							end
							haml_tag :div, :class => 'cast_bio_draft', :id => (member.gsub(" ", "_") + "_bio") do
							# contestant = Contestant.find_by_name(member)
							# haml_tag :p do
							# 	haml_tag :strong, contestant.nickname
							# 	haml_tag :br
							# 	haml_tag :b, "Tribe"
							# 	haml_tag :span, contestant.tribe
							# 	haml_tag :br
							# 	haml_tag :b, "Age"
							# 	haml_tag :span, contestant.age
							# 	haml_tag :br
							# 	haml_tag :b, "Hometown"
							# 	haml_tag :span, contestant.hometown
							# 	haml_tag :br
							# 	haml_tag :b, "Occupation"
							# 	haml_tag :span, contestant.occupation
							# 	haml_tag :br
							# 	haml_tag :b, "Reality Labs Pre-Season Rank"
							# 	haml_tag :span, contestant.preseason_rank
							# 	haml_tag :br
							# 	haml_tag :b, "The Lab Work"
							# 	haml_tag :span, :class => 'bio_float' do 
							# 		haml_concat contestant.labwork
							# 	end
							# 	haml_tag :br
							# end
							end

app/views/leagues/_refresh.html.haml
%h1 This is whose turn it is: "#{@turn}"

app/views/leagues/draft_preview.html.haml
%div.hero
  %div.hero_inset
    %h1.lc_page_heading  Draft Setup
    %div.hero_left
      %table.online_table 
        %thead
          %tr
            %th Signed In
            %th Not Signed In
        %tbody
        - @users.each do |user|
          %tr
            =online(user)
            =offline(user) 
    %div.hero_right
      %table.draft_setup_table
        %thead
          %tr
            %th{:colspan => "2"} Draft Details
        %tbody
          %tr
            %td Available Contestants
            %td= "#{@ncontestants}" 
          %tr
            %td League Members
            %td= "#{@nusers}"
          %tr
            %td Team Size 
            %td= "#{@nrounds}"
    %div.clear
    =draft_order

    =form_tag start_draft_path do
      / =hidden_field_tag "draft_order", @draft_order
      =submit_tag "Start Draft!", :id => "start_draft"

/ :javascript
/   $("#start_draft").on('click', function() {
/     $.ajax({
/     type: 'POST',
/     url: "http://localhost:9292/faye",
/     data: 'message={"channel":"/draft/start", "data":"data"}'
/     });
/   });

app/views/leagues/index.html.haml
%h1 Hello World!!!
%p 
  This is just some rando text I'm throwing up to illustrate that everything's working as it should.  Holla!  This page should appear in /leagues as the index page.

%table#leagues
  %thead
    %tr
      %th League ID
      %th League Name
      %th Confirmation Code
  %tbody
    - @leagues.each do |league|
      %tr
        %td= league.id
        %td= league.name 
        %td= league.confirmation_code

app/views/leagues/new.html.haml
%div.hero
	%div.hero_inset_image
		%h1.league_header Create New League
		= form_tag leagues_path, :id => "new_league" do
			%div.hero_left.new_user_hero_div
				%div.opacity
					%h2.league_subheader#league_subheader League Info
					%p.description#league_description Please choosse a name and confirmation code for your new leage.  You'll need to give this information to all of the friends you invite in order for them to join the league, so please write it down.  
					%p.league_field
						= label :league, :name, 'League Name', :class => "league_label name_label"
						%span#check_league_name_response.check_league_name_response 
						= text_field :league, :name, :class => "league_input required", :maxlength => "30"


					%p.league_field
						= label :league, :confirmation_code, 'Code', :class => "league_label"
						= text_field :league, :confirmation_code, :class => "league_input required"
				%div.opacity
					%h2.league_subheader#user_subheader User Info
					%p.description#user_description You'll log in for future visits with your username and password.  We ask for your email in case you need to reset your password.
					%p.league_field
						= label :user, :username, 'Username', :class => "league_label name_label"
						%span#check_username_response.check_username_response 
						= text_field :user, :username, :class => "league_input required"

					%p.league_field
						= label :user, :password, 'Password', :class => "league_label"
						= password_field :user, :password, :class => "league_input required"

					%p.league_field
						= label :user, :email, 'Email', :class => "league_label"
						= email_field :user, :email, :class => "league_input required"	

					%p.league_field.name_field
						= label :user, :first_name, 'First Name', :class => "league_label"
						= text_field :user, :first_name, :class => "league_input required", :maxlength => "30"

					%p.league_field.name_field
						= label :user, :last_name, 'Last Name', :class => "league_label"
						= text_field :user, :last_name, :class => "league_input required", :maxlength => "30"
					%div.clear
								

			%div.hero_right.new_user_hero_div
				%div.opacity
					%h2.league_subheader#invite_subheader Invite Friends
					%p.description#invite_description Invite up to 8 friends you'd like to have in your league.  Just enter their email addresses below and they will receive an invitation with your league name and confirmation code.  That's the ONLY email they'll ever receive from us, we promise!
					%p.league_field
						= label :invite, :email, 'Email Address', :class => "league_label"
						= email_field :invite, :email1, :class => "league_invite"
						= email_field :invite, :email2, :class => "league_invite"
						= email_field :invite, :email3, :class => "league_invite"
						= email_field :invite, :email4, :class => "league_invite"
						= email_field :invite, :email5, :class => "league_invite"
						= email_field :invite, :email6, :class => "league_invite"
						= email_field :invite, :email7, :class => "league_invite bottom_row"
						= email_field :invite, :email8, :class => "league_invite bottom_row"
						%div.clear
				= submit_tag 'Create New League!', :class => "new_league_submit"
				
			%div.clear
			
			

			
			

:javascript
	$(document).ready(function(){
		$('#league_subheader').on('mouseover', function(){
			$('#league_description').css('display', 'block')
		});
		$('#league_subheader').on('mouseout', function(){
			$('#league_description').css('display', 'none')
		});

		$('#user_subheader').on('mouseover', function(){
			$('#user_description').css('display', 'block')
		});
		$('#user_subheader').on('mouseout', function(){
			$('#user_description').css('display', 'none')
		});

		$('#invite_subheader').on('mouseover', function(){
			$('#invite_description').css('display', 'block')
		});
		$('#invite_subheader').on('mouseout', function(){
			$('#invite_description').css('display', 'none')
		});

		//$('#league_name').bind('change', function () {
			//var league_name = $('#league_name').val()
			//$('textarea').val(function(index, value){
				//var new_name = value.replace("Your League Name", league_name)
				//return new_name
			//});
		//});

		//$('#league_confirmation_code').bind('change', function () {
			//var league_code = $('#league_confirmation_code').val()
			//$('textarea').val(function(index, value){
				//var new_code = value.replace("Your League Code", league_code)
				//return new_code
			//});
		//});

		// This calls front-end validation on the form using the jQuery validate plugin
	    $('#new_league').validate()

	    // This checks the availability of the league name in realtime
	    $('#league_name').change(function(){
	      var username = $(this).val()
	      $.ajax({
	          type: "POST", 
	          url: "check_league_name", 
	          data: {new_name: username},
	          dataType: 'script',
	          success: function(){
	            var str = $('#league_name').val()
	            var pat = /^[a-zA-Z0-9  \-\_]+$/
	            // This makes it impossible to submit the form if the league name is not available
	            if ($('#check_league_name_response').text() == "already taken") {
	              $('.new_league_submit').attr('disabled', true)
	            }
	            else if (pat.test(str) == false) {
	              $('#check_username_response').text('letters and numbers only').addClass('username_unavailable').removeClass('username_available')
	              $('.new_league_submit').attr('disabled', true)
	            }
	            else {
	              $('.new_league_submit').attr('disabled', false)
	            }

	          }
	      });
	    });

	    // This checks the availability of the username in realtime
	    $('#user_username').change(function(){
	      var username = $(this).val()
	      $.ajax({
	          type: "POST", 
	          url: "/check_username", 
	          data: {new_name: username},
	          dataType: 'script',
	          success: function(){
	            var str = $('#user_username').val()
	            var pat = /^[a-zA-Z0-9\-]+$/
	            // This makes it impossible to submit the form if the username is not available
	            if ($('#check_username_response').text() == "already taken") {
	              $('.new_league_submit').attr('disabled', true)
	            }
	            else if (pat.test(str) == false) {
	              $('#check_username_response').text('letters and numbers only').addClass('username_unavailable').removeClass('username_available')
	              $('.new_league_submit').attr('disabled', true)
	            }
	            else {
	              $('.new_league_submit').attr('disabled', false)
	            }

	          }
	      });
	    });

	})

app/views/leagues/show.html.haml
%h1= @league.name