config/routes.rb
Realitylabs::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "start_league" => 'leagues#new', :as => 'start_league'
  post "leagues/:id/start_draft" => 'leagues#start_draft', :as => 'start_draft'
  get 'leagues/:id/draft' => 'leagues#draft', :as => 'draft'
  post "leagues/:id/add_to_team" => 'leagues#add_to_team', :as => 'add_to_team'  
  post "users/:id/delete_user" => 'users#delete_user', :as => 'delete_user'
  get 'users/:id/first_visit' => 'users#first_visit', :as => 'first_visit'
  post 'check_username' => 'users#check_username', :as => 'check_username'
  post 'leagues/check_league_name' => 'leagues#check_league_name', :as => 'check_league_name'
  post 'leagues/:id/end_draft' => 'leagues#end_draft', :as => 'end_draft'

  match 'contestants/add_round' => 'contestants#add_round'
  match 'contestants/update_round' => 'contestants#update_round'
  match 'contestants/reverse_round' => 'contestants#reverse_round'
  match '/admin' => 'contestants#index'
  match 'leagues/:id/add_to_team' => 'leagues#add_to_team'

  resources :users, :sessions, :password_resets
  resources :contestants do
    collection do
      get 'add_round'
      put 'update_round'
      get 'reverse_round'
    end
  end
  resources :leagues do
    member do
      get 'draft'
      get 'draft_preview'
    end
  end

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	# This creates an array of all contestant names for 'meet_the_cast' helper method.
      @contestants = []
      Contestant.all.each do |x|
        @contestants << x.name
      end


  	if current_user == nil 
  		@username = 'none'
  		@id = "log_in"
  	else
  		@username = current_user.username
  		@id = current_user.id
  	end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
	def meet_the_cast
		capture_haml do
			@contestants.each do |member|
				if (@contestants.index(member) % 3) == 0
					haml_tag :div, :class => 'left_col' do
						haml_tag :div, :id => member.gsub(" ", "_"), :class => 'cast_pics' do
							filename = "contestants/" + member.gsub(" ", "_") + ".jpg"
							haml_concat image_tag filename
							haml_tag :h4, member
						end
						haml_tag :div, :class => 'cast_bio', :id => (member.gsub(" ", "_") + "_bio") do
							# contestant = Contestant.find_by_name(member)
							# haml_tag :p do
							# 	haml_tag :strong, contestant.nickname
							# 	haml_tag :br
							# 	haml_tag :b, "Tribe"
							# 	haml_tag :span, contestant.tribe
							# 	haml_tag :br
							# 	haml_tag :b, "Age"
							# 	haml_tag :span, contestant.age
							# 	haml_tag :br
							# 	haml_tag :b, "Hometown"
							# 	haml_tag :span, contestant.hometown
							# 	haml_tag :br
							# 	haml_tag :b, "Occupation"
							# 	haml_tag :span, contestant.occupation
							# 	haml_tag :br
							# 	haml_tag :b, "Reality Labs Pre-Season Rank"
							# 	haml_tag :span, contestant.preseason_rank
							# 	haml_tag :br
							# 	haml_tag :b, "The Lab Work"
							# 	haml_tag :span, :class => 'bio_float' do 
							# 		haml_concat contestant.labwork
							# 	end
							# 	haml_tag :br
							# end
						end
					end
				elsif (@contestants.index(member) % 3) == 1
					haml_tag :div, :class => 'center_col' do
						haml_tag :div, :id => member.gsub(" ", "_"), :class => 'cast_pics' do
							filename = "contestants/" + member.gsub(" ", "_") + ".jpg"
							haml_concat image_tag filename
							haml_tag :h4, member
						end
						haml_tag :div, :class => 'cast_bio', :id => (member.gsub(" ", "_") + "_bio") do
							# contestant = Contestant.find_by_name(member)
							# haml_tag :p do
							# 	haml_tag :strong, contestant.nickname
							# 	haml_tag :br
							# 	haml_tag :b, "Tribe"
							# 	haml_tag :span, contestant.tribe
							# 	haml_tag :br
							# 	haml_tag :b, "Age"
							# 	haml_tag :span, contestant.age
							# 	haml_tag :br
							# 	haml_tag :b, "Hometown"
							# 	haml_tag :span, contestant.hometown
							# 	haml_tag :br
							# 	haml_tag :b, "Occupation"
							# 	haml_tag :span, contestant.occupation
							# 	haml_tag :br
							# 	haml_tag :b, "Reality Labs Pre-Season Rank"
							# 	haml_tag :span, contestant.preseason_rank
							# 	haml_tag :br
							# 	haml_tag :b, "The Lab Work"
							# 	haml_tag :span, :class => 'bio_float' do 
							# 		haml_concat contestant.labwork
							# 	end
							# 	haml_tag :br
							# end
						end
					end
				else
					haml_tag :div, :class => 'right_col' do
						haml_tag :div, :id => member.gsub(" ", "_"), :class => 'cast_pics' do
							filename = "contestants/" + member.gsub(" ", "_") + ".jpg"
							haml_concat image_tag filename
							haml_tag :h4, member
						end
						haml_tag :div, :class => 'cast_bio', :id => (member.gsub(" ", "_") + "_bio") do
							# contestant = Contestant.find_by_name(member)
							# haml_tag :p do
							# 	haml_tag :strong, contestant.nickname
							# 	haml_tag :br
							# 	haml_tag :b, "Tribe"
							# 	haml_tag :span, contestant.tribe
							# 	haml_tag :br
							# 	haml_tag :b, "Age"
							# 	haml_tag :span, contestant.age
							# 	haml_tag :br
							# 	haml_tag :b, "Hometown"
							# 	haml_tag :span, contestant.hometown
							# 	haml_tag :br
							# 	haml_tag :b, "Occupation"
							# 	haml_tag :span, contestant.occupation
							# 	haml_tag :br
							# 	haml_tag :b, "Reality Labs Pre-Season Rank"
							# 	haml_tag :span, contestant.preseason_rank
							# 	haml_tag :br
							# 	haml_tag :b, "The Lab Work"
							# 	haml_tag :span, :class => 'bio_float' do 
							# 		haml_concat contestant.labwork
							# 	end
							# 	haml_tag :br
							# end
						end
					end
				end
			end
		end
	end
end

app/views/welcome/index_working.html.haml
%div.bg_elements
  %header.main_header
    %div.rl_logo= image_tag('rl_logo.png', :alt => "Reality Labs")
    %div.surv_logo= image_tag('surv_logo.png', :alt => "Survivor Fantasy League")
    %div.signin= link_to 'Sign In', log_in_path
    %div.signout
      Logged in as #{@username}
      %p= link_to "Log out", log_out_path
    %div.clear
  %div.main
    %div.hero
      =image_tag('left-scroll.png', :class => 'left_scroll', :id => 'left_scroll')
      =image_tag('right-scroll.png', :class => 'right_scroll', :id => 'right_scroll')
      %div#hero.pics
        =image_tag('hero_4.jpg')
        =image_tag('hero_5.jpg')
        =image_tag('hero_6.jpg')
      =image_tag('whitearrow.png', :class => 'arrow', :id => 'arrow')
      %div.handwriting Click Here to Begin...
    / %div.play_button Start the Fantasy
    %button.hero_button Start Now!
    %div.bottom_content 
      %div.about
        %h1 Outwit - Outplay - Outlast
        %p Welcome to Reality Lab's Survivor Fantasy Game!  The game takes all the aspects of fantasy sports leagues that you love and brings them to the world of reality tv.  Start a league and invite your friends.  Pick Survivor contenders to be on your team through a realtime draft with other folks in your league.  Earn points based on how your team members perform each week.  Whoever has the most points at the end of the season wins!  
      %div.rules
        %h1 Gameplay
        %h2 Setting Up
        %p This is a description of how the user either creates a league and invites friends or joins a league that's already been created. 
        %h2 The Draft
        %p This describes the intricacies of the draft.
        %h2 Regular Gameplay
        %p This describes how scoring works during regular gameplay and how a winner is determined.
      %div.cast  
        %h1 Meet the Cast
        %p 
          This is where the content for Meet the Cast will go.  It will look just like this: 
          =link_to 'CBS Cast Bios', 'http://www.cbs.com/shows/survivor/cast/'
    %div.sidebar 
      %ul
        %li#about About
        %li#rules How to Play
        %li#cast Meet the Cast
        %li#my_survivor My Survivor

    %div.clear
%div.start_game
  %div.new_league
    %button#new_league Start a league
    %p Become the League Commissioner and Invite Your Friends
  %div.new_user
    %button#new_user Join a League
    %p Click Here if You Have a Confirmation Code from a Friend
  %div.clear
:javascript 
  if ("#{@id}" !== "log_in") {
    $('.signin').css('display', 'none')
    $('.signout').css('display', 'block')
  }

  $('.hero_button').on("click", function(){
    $('.start_game').css("display", "block")
  })

  $('#hero').cycle({ 
    fx:     'fade', 
    speed:  'slow', 
    timeout: 5000, 
    next:   '#right_scroll', 
    prev:   '#left_scroll' 
  });

  $('#new_league').on('click', function() {
    window.location.href = "/leagues/new"
  })

  $('#new_user').on('click', function() {
    window.location.href = "/users/new"
  })

  $('#about').on('click', function() {
    $('div.bottom_content > div').css('display', 'none')
    $('.about').css('display', 'block')
  })

  $('#rules').on('click', function() {
    $('div.bottom_content > div').css('display', 'none')
    $('.rules').css('display', 'block')
  })

  $('#cast').on('click', function() {
    $('div.bottom_content > div').css('display', 'none')
    $('.cast').css('display', 'block')
  })

  $('#my_survivor').on('click', function() {
    window.location.href = "/users/#{@id}"
  })